
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install cmake

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build